# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "estore_conventions"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Callahan"]
  s.date = "2013-10-16"
  s.description = "abstracting out things"
  s.email = "andrew.callahan@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "estore_conventions.gemspec",
    "lib/estore_conventions.rb",
    "lib/estore_conventions/builder.rb",
    "spec/lib/data_object_builder_spec.rb",
    "spec/lib/factory_build_for_store_spec.rb",
    "spec/lib/sorted_values_spec.rb",
    "spec/lib/t_id_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/andrewcallahan/estore_conventions"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.5"
  s.summary = "abstracting out things"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_runtime_dependency(%q<aggtive_record>, [">= 0"])
      s.add_runtime_dependency(%q<active_record_content_blob>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.2.14"])
      s.add_development_dependency(%q<paper_trail>, [">= 0"])
    else
      s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_dependency(%q<aggtive_record>, [">= 0"])
      s.add_dependency(%q<active_record_content_blob>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.2.14"])
      s.add_dependency(%q<paper_trail>, [">= 0"])
    end
  else
    s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
    s.add_dependency(%q<aggtive_record>, [">= 0"])
    s.add_dependency(%q<active_record_content_blob>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.2.14"])
    s.add_dependency(%q<paper_trail>, [">= 0"])
  end
end

